// Code is generated by goas. DO NOT EDIT!

package handlers

import (
	"net/url"
)

func parseParametersPetIDInPath(query url.Values) (out string, err error) {
	var v string
	vs, ok := query["petID"]
	if ok && len(vs) > 0 {
		v = vs[0]
	}
	if !ok {
		return "", ErrFieldIsRequired{Field: "petID"}
	}

	if ok {
		out = v
	}

	return
}
