// Code is generated by goas. DO NOT EDIT!

package handlers

import (
	"encoding/json"
	"net/http"
)

// PetsPetIDDeleteFunc ...
type PetsPetIDDeleteFunc func(PetsPetIDDeleteRequest) PetsPetIDDeleteResponser

// PetsPetIDDeleteHandlerFunc ...
func PetsPetIDDeleteHandlerFunc(fn PetsPetIDDeleteFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req PetsPetIDDeleteRequest
		var err error
		_ = err

		fn(req).write(w)
	}
}

// PetsPetIDDeleteErrorHandler ...
var PetsPetIDDeleteErrorHandler = ErrorHandler

// PetsPetIDDeleteRequest ...
type PetsPetIDDeleteRequest struct {
	Path struct {
		PetID string
	}
}

// PetsPetIDDeleteResponser ...
type PetsPetIDDeleteResponser interface {
	write(http.ResponseWriter)
	petspetiddeleteresponseinterface()
}

// PetsPetIDDeleteResponseJSON200 ...
func PetsPetIDDeleteResponseJSON200() PetsPetIDDeleteResponser {
	var w petsPetIDDeleteJSONResponse
	w.StatusCode = 200
	return w
}

// PetsPetIDDeleteResponseJSONDefault ...
func PetsPetIDDeleteResponseJSONDefault(resp Error) PetsPetIDDeleteResponser {
	var w petsPetIDDeleteJSONResponse
	w.Obj = resp
	return w
}

// --- Response interface ---

type petsPetIDDeleteJSONResponse struct {
	StatusCode int
	Obj        interface{}
}

var _ PetsPetIDDeleteResponser = (*petsPetIDDeleteJSONResponse)(nil)

func (rw petsPetIDDeleteJSONResponse) petspetiddeleteresponseinterface() {}

func (rw petsPetIDDeleteJSONResponse) write(w http.ResponseWriter) {
	w.WriteHeader(rw.StatusCode)
	err := json.NewEncoder(w).Encode(rw.Obj)
	if err != nil {
		JSONError(err)
	}
}
