// Code is generated by goas. DO NOT EDIT!

package handlers

// Error - ...
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Pet - ...
type Pet struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Tag  string `json:"tag"`
}

// PetCreateBody - ...
type PetCreateBody struct {
	Name string `json:"name"`
	Tag  string `json:"tag"`
}

// PetPatchBody - ...
type PetPatchBody struct {
	Name string `json:"name"`
	Tag  string `json:"tag"`
}

// Pets - ...
type Pets []Pet
